### ISSUE TITLE
cliend id

### ISSUE THREAD

**Issue by Ravi753208** [Ayush-Kanduri/Placement-Cell-Application#1]
![image](https://user-images.githubusercontent.com/87948123/208404021-5367f319-7013-4e1c-b7d2-55a6cf75d31f.png)

**Comment by Ayush-Kanduri** [comment]
Set up a project on Google Developer Console. 
Set a Client ID for the same. 
Put that Client ID inside the .env file as per the given format in the ENV_FORMAT.json
