### ISSUE TITLE
how to run project

### ISSUE THREAD

**Issue by udayvarmora07** [Ayush-Kanduri/Placement-Cell-Application#2]
can you make video of how to run project

**Comment by Rahul4578** [comment]
> can you make video of how to run project

bro , you have ran it

**Comment by Ayush-Kanduri** [comment]
Instruction already given on the Repo's Readme.

**Comment by udayvarmora07** [comment]
Thank you for your response

**Comment by Rahul4578** [comment]
Hello I am unable to run this code  please make a video running the code as I am new in this .I have given this project as major project in my college.please help ayush bhaiya 🙃

**Comment by Ayush-Kanduri** [comment]
I have already made a video on this project.

https://youtu.be/JI-lPvpq-WI?si=wWut7HU3YFpD2jRU

Rest you can check the project by running on your system.
Instruction given on the repo readme.

**Comment by Rahul4578** [comment]
I am not able to do the setup 😒

**Comment by Ayush-Kanduri** [comment]
Have you followed the instructions given on the repository?
If yes, then what is the error you're getting?

**Comment by Rahul4578** [comment]
Please provide instructions more specific I am not able to follow them.

**Comment by Ayush-Kanduri** [comment]
Instructions are already given specifically. Read carefully. 
Where is it that you're stuck? You have to be clear & precise as per where you're getting the issue or what's the error. How would I be able to know on what part you're getting the problem.

**Comment by Rahul4578** [comment]
From create env this step I am not able to do.
Create '.env' file & Set the Environment Variables in it, as per the 'ENV_FORMAT.json' file.
Run 'npm install' in GitBash Terminal
If you want to run the project in development mode locally then go to '.env' file & set,
ENVIRONMENT=development
DEPLOYMENT=local
If you want to run the project in production mode then go to '.env' file & set,
ENVIRONMENT=production
DEPLOYMENT=local/other/Heroku/AWS
For Development Mode:
Run 'npm run dev_start' in GitBash Terminal

**Comment by Ayush-Kanduri** [comment]
I'm assuming you know how to access Google cloud console which is a prerequisite for the Passport Google Auth. 
Now, You have to 
1. configure node, MongoDB.
2. create a google project in the Google cloud console.
Under Apis & services, create credentials and oauth screen for the Google callback redirect.
3. set the client id, secret, url of the above Google project in the environment file.

If you don't know how to create Google project & its client id, i would recommend you to watch any tutorial on the same on YouTube.

**Comment by Rahul4578** [comment]
Thanks a lot bhaiya
